package interfaz;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import utilerias.AccionReporte;
import utilerias.Conexion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 05C4R
 */
public class Reportes extends javax.swing.JFrame  {
private boolean reporteProducto;
private AccionReporte reporte;
private  Map parametros;
Thread hilo;
Thread hilo1;
 Date fechaActual=new Date();
 Conexion con = new Conexion("root", "05C4R");
DefaultTableModel modelo;
 AccionReporte report;
    int idventa = 0;
    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        this.setLocationRelativeTo(null);
        delDateChooser.setMaxSelectableDate(fechaActual);
        alDateChooser.setMaxSelectableDate(fechaActual);
        reporte=new AccionReporte();
        parametros=new HashMap();
        diariasRadioButton.setSelected(true);
        alDateChooser.setVisible(false);
        delDateChooser.setDate(fechaActual);
        jLabel2.setVisible(false);
        listaProductoRadioButton.setSelected(true);
         jProgressBar1.setVisible(false);
          jProgressBar2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventasbuttonGroup = new javax.swing.ButtonGroup();
        productosbuttonGroup = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        generar = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        listaProductoRadioButton = new javax.swing.JRadioButton();
        agotadosRadioButton = new javax.swing.JRadioButton();
        generarProductosButton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        cargandoLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        generarVentasButton = new javax.swing.JButton();
        delDateChooser = new com.toedter.calendar.JDateChooser();
        alDateChooser = new com.toedter.calendar.JDateChooser();
        diariasRadioButton = new javax.swing.JRadioButton();
        porPeriodoRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rfcTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        buscarButton = new javax.swing.JButton();

        generar.setText("generar");
        generar.setActionCommand("generarMenuItem");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(generar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productosbuttonGroup.add(listaProductoRadioButton);
        listaProductoRadioButton.setText("Lista de Productos");
        listaProductoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaProductoRadioButtonActionPerformed(evt);
            }
        });

        productosbuttonGroup.add(agotadosRadioButton);
        agotadosRadioButton.setText("Productos Agotados");
        agotadosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agotadosRadioButtonActionPerformed(evt);
            }
        });

        generarProductosButton.setText("Generar");
        generarProductosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarProductosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agotadosRadioButton)
                            .addComponent(listaProductoRadioButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generarProductosButton)
                            .addComponent(cargandoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(listaProductoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agotadosRadioButton)
                .addGap(38, 38, 38)
                .addComponent(generarProductosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cargandoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Productos", jPanel2);

        generarVentasButton.setText("Generar");
        generarVentasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarVentasButtonActionPerformed(evt);
            }
        });

        ventasbuttonGroup.add(diariasRadioButton);
        diariasRadioButton.setText("Diarias");
        diariasRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diariasRadioButtonActionPerformed(evt);
            }
        });

        ventasbuttonGroup.add(porPeriodoRadioButton2);
        porPeriodoRadioButton2.setText("Por Periodo");
        porPeriodoRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porPeriodoRadioButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Del");

        jLabel2.setText("Al");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(porPeriodoRadioButton2)
                            .addComponent(diariasRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(alDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(delDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(generarVentasButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diariasRadioButton)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(porPeriodoRadioButton2)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(delDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(generarVentasButton)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Ventas", jPanel1);

        jLabel3.setText("RFC");

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NumDeVenta", "Fecha", "Hora", "Total"
            }
        ));
        tablaVentas.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tablaVentas);

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rfcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rfcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Re Expedicion ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarVentasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarVentasButtonActionPerformed
        Date fechaInicial;
        Date fechaFinal;
        TareaVisualiza tarea;
        jcThread progreso=new jcThread(this.jProgressBar2,this.cargandoLabel);
        if (diariasRadioButton.isSelected()) {
            fechaInicial = delDateChooser.getDate();
            parametros.put("fechaInicial", fechaInicial);
            //reporte.visualizarPDF("src/reportes/VentasDiarias.jasper", "Venta Diaria", parametros);
            tarea=new TareaVisualiza("src/reportes/VentasDiarias.jasper", "Venta Diaria", parametros);
        } else {
            fechaInicial = delDateChooser.getDate();
            fechaFinal = alDateChooser.getDate();
            //SimpleDateFormat fechaformato = new SimpleDateFormat("yyyy-MM-dd");
            parametros.put("fechaInicial",fechaInicial);
             parametros.put("fechaFinal", fechaFinal);
             //System.out.println("reporte en conctruccion");
             tarea=new TareaVisualiza("src/reportes/VentaPorPeriodo.jasper", "Venta Diaria", parametros);
            //reporte.visualizarPDF("src/reportes/VentaPorPeriodo.jasper", "Ventas Por Periodo", parametros);

        }
         hilo1=new Thread(tarea);
       hilo=new Thread(progreso);
       
        hilo1.start();
            hilo.start();
    }//GEN-LAST:event_generarVentasButtonActionPerformed

    private void listaProductoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaProductoRadioButtonActionPerformed
        reporteProducto=true;
    }//GEN-LAST:event_listaProductoRadioButtonActionPerformed

    private void agotadosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agotadosRadioButtonActionPerformed
         reporteProducto=false;
    }//GEN-LAST:event_agotadosRadioButtonActionPerformed

    private void generarProductosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarProductosButtonActionPerformed
       TareaVisualiza tarea;
        jcThread progreso=new jcThread(this.jProgressBar1,this.cargandoLabel);
      // Job tarea=new Job("src/reportes/Productos.jasper","Lista de Produtos",null);
       //hilo=new Thread(progreso);
       //hilo1=new Thread(tarea);
       // hilo1.start();
        //this.dispose();
        if ( listaProductoRadioButton.isSelected()) {
             tarea=new TareaVisualiza("src/reportes/Productos.jasper","Lista de Produtos",null);            
            //reporte.visualizarPDF("src/reportes/Productos.jasper","Lista de Produtos",null);      
       
        }else{
        //reporte.visualizarPDF("src/reportes/ProductosAgotados.jasper","Lista de Produtos Agotados",null);
        tarea=new TareaVisualiza("src/reportes/Productos.jasper","Lista de Produtos",null);
        }
        hilo1=new Thread(tarea);
       hilo=new Thread(progreso);
       
        hilo1.start();
            hilo.start();
    }//GEN-LAST:event_generarProductosButtonActionPerformed

    private void diariasRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diariasRadioButtonActionPerformed
        // TODO add your handling code here:
         alDateChooser.setVisible(false);
        jLabel2.setVisible(false);
        alDateChooser.setDate(fechaActual);
    }//GEN-LAST:event_diariasRadioButtonActionPerformed

    private void porPeriodoRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porPeriodoRadioButton2ActionPerformed
        // TODO add your handling code here:
        alDateChooser.setVisible(true);
        jLabel2.setVisible(true);
        alDateChooser.setDate(fechaActual);
        delDateChooser.setDate(fechaActual);
    }//GEN-LAST:event_porPeriodoRadioButton2ActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
    try {
        // TODO add your handling code here:
        ResultSet r;
         Object datos[]=new Object[4];
         modelo = (DefaultTableModel)tablaVentas.getModel();
        con.conectar();
        r = con.consultar("SELECT   *,cli.rfc AS Cliente     "+
   "FROM Venta ven"
                + " INNER JOIN  Cliente cli ON cli.id_cliente = ven.Cliente_id_cliente where cli.rfc = '" + rfcTxt.getText() + "'");
        //r = con.consultar("SELECT * FROM venta where id_cliente FROM Cliente where rfc = '" + rfcTxt.getText() + "'");
        while (r.next()) {
            datos[0]=r.getObject("id_venta");
            datos[1]=r.getObject("fecha");
            datos[2]=r.getObject("hora");
            datos[3]=r.getObject("total");
            modelo.addRow(datos);
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        // TODO add your handling code here:
        
        parametros.put("id_venta",modelo.getValueAt(tablaVentas.getSelectedRow(), 0) );
            System.out.println("");
        report.generarPDF("src/reportes/Factura.jasper", "src/Comprobante.pdf", parametros);
    }//GEN-LAST:event_generarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton agotadosRadioButton;
    private com.toedter.calendar.JDateChooser alDateChooser;
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel cargandoLabel;
    private com.toedter.calendar.JDateChooser delDateChooser;
    private javax.swing.JRadioButton diariasRadioButton;
    private javax.swing.JMenuItem generar;
    private javax.swing.JButton generarProductosButton;
    private javax.swing.JButton generarVentasButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton listaProductoRadioButton;
    private javax.swing.JRadioButton porPeriodoRadioButton2;
    private javax.swing.ButtonGroup productosbuttonGroup;
    private javax.swing.JTextField rfcTxt;
    private javax.swing.JTable tablaVentas;
    private javax.swing.ButtonGroup ventasbuttonGroup;
    // End of variables declaration//GEN-END:variables
}
